### PR TITLE
Make Request timeout configurable 

### PR DESCRIPTION
**Pull request by AR1011**
increase request timeout to 1 second + fix cluster example build output names in the makefile

### CODE REVIEW

**Comment by perbu** [comment]
Timeouts should really be configurable, imho. This ain't the way.

**Comment by AR1011** [comment]
@perbu I agree

**Comment by anthdm** [comment]
@AR1011 We could pass a config to NewSelfmanaged()

**Comment by perbu** [comment]
Looks good.

**Review by perbu — APPROVED** [review]
all pretty straight forward.

**Pull request merged**
