### PR TITLE
Functional options pattern for Engine init.

### PR DESCRIPTION
**Pull request by perbu**
Implemented.

pidseparator is currently a global variable so it looks a bit weird.

also, not sure about naming.

### CODE REVIEW

**Comment by anthdm** [comment]
@perbu `pathSeparator`? What do you propose?

**Comment by perbu** [comment]
@anthdm I suggest we leave it is as it is. It's a global variable, but it doesn't cause any issues. The alternative would be to export it and let users set it directly.

**Comment by anthdm** [comment]
@perbu This looks good. Ready for merge?

**Comment by perbu** [comment]
Yes. Go ahead.

**Comment by anthdm** [comment]
@perbu You are HIM. Thank you again!

**Pull request merged**
