### PR TITLE
PIDS generate id automatically if not given one

### PR DESCRIPTION
**Pull request by anthdm**

### CODE REVIEW

**Review by perbu — APPROVED** [review]
look good. it would be nice to know the motiation for doing the change, though.

**Comment by tprifti** [comment]
> look good. it would be nice to know the motiation for doing the change, though.

There was a long discussion on Discord about this. Most important change is that you can spawn an actor without specifying ID.

**Review by tprifti — APPROVED** [review]

**Comment by anthdm** [comment]
@perbu Couple things that made me do this.

1. It is very common to spawn more actors of the same "type/kind/domain" (player, inventory, db, lobby, connection). So spawning the same actor type over and over again would conflict with the registry, unless the user provides a custom ID. If the user does not provide an ID then we just create an unique one ourselves.

2. A PID should be very simple (address and id). WithTags was just a fancy term for creating a single string.

**Comment by anthdm** [comment]
@tprifti This breaks stuff if you are using WithTags in prod. But like I mentioned. We are freezing the API very soon.

**Pull request merged**
