### PR TITLE
replace logrus with log/slog from stdlib

### PR DESCRIPTION
**Pull request by perbu**
The default now is not to log anything.
So, if the application needs logging, it wouldn't do this:
```
	engine := actor.NewEngine()
```
but rather
```
	engine := actor.NewEngine(actor.Config{Logger: log.Default()})
```
for the default logging (which can be changed)
or for more control:
```
	lh := log.NewHandler(os.Stdout, log.JsonFormat, slog.LevelDebug)
	engine := actor.NewEngine(actor.Config{Logger: log.NewLogger("[engine]", lh)})
```

Since slog is so versatile this should be good enough for anybody.

No big semantic changes. I did remove the log.Fatal and log.Panic-level and replaces these with panics.
Removes uses of the log package from the examples, they shouldn't be using the library for logging, but rather log directly with log or slog.

Note that one test is failing, it was failing before as well. 

Overall, I like the package. God job.

Closes: #54

### CODE REVIEW

**Comment by anthdm** [comment]
@perbu Looking into this right now. Thanks for this upfront!

**Review by anthdm — CHANGES_REQUESTED** [review]
Thank you for this amazing PR. Just one minor thing that could be very helpful, is to add some documentation in the README about on how to use the logger maybe?

**Review by perbu — COMMENTED** [review]
requested changes done.

**Comment by perbu** [comment]
> Thank you for this amazing PR. Just one minor thing that could be very helpful, is to add some documentation in the README about on how to use the logger maybe?

Hmm. How do I tell github that I did what you asked? 😕

**Comment by anthdm** [comment]
> > Thank you for this amazing PR. Just one minor thing that could be very helpful, is to add some documentation in the README about on how to use the logger maybe?
> 
> Hmm. How do I tell github that I did what you asked? 😕

IDK :)

**Comment by anthdm** [comment]
For some reason its not willing to pass the build system, due to some slog package shenanigans. Would be cool if you could look into that.

**Comment by perbu** [comment]
@anthdm I don't see any problems with the CI anymore. I've bumped the GH action to use 1.20, that was the ticket.

**Pull request merged**
