### PR TITLE
Contructors, examples

### PR DESCRIPTION
**Pull request by perbu**
So, I changed the engine and remote constructor according to https://github.com/anthdm/hollywood/issues/114.

So now these are consistent. I'll do the cluster too, but maybe in another PR as this one is already quite big.

I've also fixed all the remote examples, including the mdns-example, which was completely broken. It's actually quite cool.

Hopefully this should be one of the last breaking changes we'll do.

### CODE REVIEW

**Comment by anthdm** [comment]
@perbu I merged the remote examples first, which conflicts here apparantly

**Comment by perbu** [comment]
Don't worry about it. I'll fix it on my end.

**Comment by perbu** [comment]
oh. I need to fix the README again.

**Comment by anthdm** [comment]
Let me know if you are happy with the README, I will merge after.

**Comment by perbu** [comment]
Now it should be good. benchmark also fixed and the output is shown in the readme.

**Pull request merged**
