### PR TITLE
Remove redis dependency

### PR DESCRIPTION
**Pull request by perbu**
This PR removes the redis depency by altering the persistence example to use file storage instead.

### CODE REVIEW

**Comment by perbu** [comment]
This closes #68 .

**Comment by ValentinMontmirail** [comment]
Well isn't the question more: why are dependencies from examples listed inside the official go.mod of the repo? There is no other way to avoid that than simply not using Redis in examples?

**Comment by tprifti** [comment]
> Well isn't the question more: why are dependencies from examples listed inside the official go.mod of the repo? There is no other way to avoid that than simply not using Redis in examples?

You could create go.mod inside the examples but the issue is that each example will need to sync with latest version of hollywood version each time there is a new release.

**Comment by perbu** [comment]
> Well isn't the question more: why are dependencies from examples listed inside the official go.mod of the repo? There is no other way to avoid that than simply not using Redis in examples?

If you take a look at the linked issue there is some discussion there. The least worst alternative was to remove the dependencies.

**Pull request merged**
