### PR TITLE
Completion of the PID hasTag function

### PR DESCRIPTION
**Pull request by MansourBaitar**
When going through the code base, I saw that the function returned a instant panic.

Nothing to worry about since the function wasn't in use.
I've taken it upon myself to complete this small & easy function.

I believe you guys will know where you can use this function.

### CODE REVIEW

**Comment by perbu** [comment]
Thanks! I think I fixed this in the deadletter actor PR, sorry.

**Comment by MansourBaitar** [comment]
@perbu I've just tried your hasTag function.
This will work if there are nested tags and you want to find one of the nested tags.

I've created a playground file thats shows you the result if you try to get a tag that is at the end of the pid.ID

It will return false, when it should return true.
I believe you have to split the ID on the pidSeperator and then look if it contains the given tag.

https://go.dev/play/p/OB8So6NyYYR

**Comment by perbu** [comment]
I think you're right and I think I introduced a bug. Perhaps you wanna rebase on master?

**Comment by MansourBaitar** [comment]
Rebased on master done!

**Comment by MansourBaitar** [comment]
@anthdm I believe this is ready to be merged to master

**Pull request merged**
